#!/usr/bin/env bash
set -euo pipefail

if [[ ${EUID:-$(id -u)} -ne 0 ]]; then
  echo "Run this script as root after the instructor has validated course.env." >&2
  echo "Example: sudo $0" >&2
  exit 1
fi

source_env=${1:-/home/ubuntu/.config/nchc-cudaq-course/course.env}
destination=${2:-/opt/nchc-cudaq-course/activity/activity-keys.env}

[[ -f "$source_env" ]] || {
  echo "Validated course env not found: $source_env" >&2
  echo "Complete configure-course-env.sh and verification first." >&2
  exit 1
}

set -a
# Generated by configure-course-env.sh and treated as trusted instructor input.
# shellcheck disable=SC1090
source "$source_env"
set +a

nemotron_key=${RAP_NEMOTRON_3_ULTRA_API_KEY:-${RAP_NENOTRON_3_ULTRA_API_KEY:-}}
: "${nemotron_key:?Nemotron activity key is missing}"
: "${RAP_GEMMA_26B_API_KEY:?Gemma 26B activity key is missing}"
: "${RAP_GEMMA_31B_API_KEY:?Gemma 31B activity key is missing}"

for secret_value in \
  "$nemotron_key" \
  "$RAP_GEMMA_26B_API_KEY" \
  "$RAP_GEMMA_31B_API_KEY" \
  "${NVIDIA_NIM_API_KEY:-}"; do
  [[ "$secret_value" != *$'\n'* && "$secret_value" != *' '* ]] || {
    echo "API keys must not contain spaces or newlines." >&2
    exit 1
  }
done

temporary_env=$(mktemp /run/nchc-activity-keys.XXXXXX)
trap 'rm -f "$temporary_env"' EXIT
umask 077
{
  printf 'RAP_NEMOTRON_3_ULTRA_API_KEY=%s\n' "$nemotron_key"
  printf 'RAP_NENOTRON_3_ULTRA_API_KEY=%s\n' "$nemotron_key"
  printf 'RAP_GEMMA_26B_API_KEY=%s\n' "$RAP_GEMMA_26B_API_KEY"
  printf 'RAP_GEMMA_31B_API_KEY=%s\n' "$RAP_GEMMA_31B_API_KEY"
  printf 'NVIDIA_NIM_API_KEY=%s\n' "${NVIDIA_NIM_API_KEY:-}"
} > "$temporary_env"

install -d -m 0700 -o root -g root "$(dirname "$destination")"
install -m 0600 -o root -g root "$temporary_env" "$destination"
unset nemotron_key secret_value RAP_NEMOTRON_3_ULTRA_API_KEY \
  RAP_NENOTRON_3_ULTRA_API_KEY RAP_GEMMA_26B_API_KEY \
  RAP_GEMMA_31B_API_KEY NVIDIA_NIM_API_KEY

echo "Activity credential bundle installed: $destination (mode 600, root-only)."
echo "It is intentionally included in the VM image and is recoverable by VM administrators."
echo "Revoke every bundled key immediately after the event."
